services:
  nginx:
    image: nginx:alpine
    container_name: nginx
    depends_on:
      - moodle
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/html:/usr/share/nginx/html
    restart: always

  moodle:
    image: bitnami/moodle:latest
    container_name: moodle
    depends_on:
      - mariadb
    expose:
      - "8080"
    environment:
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_EMAIL=${MOODLE_EMAIL}
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=${MARIADB_DATABASE}
      - MOODLE_DATABASE_USER=${MARIADB_USER}
      - MOODLE_DATABASE_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - ./data/moodle:/bitnami/moodle
      - ./data/moodledata:/bitnami/moodledata
    restart: always

  mariadb:
    image: bitnami/mariadb:latest
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - ./data/mariadb:/bitnami/mariadb
    restart: always

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/html:/usr/share/nginx/html
    entrypoint: ""  # Keeps it from auto-running
