services:
  nginx:
    image: nginx:1.25-alpine
    container_name: nginx
    depends_on:
      - moodle
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/html:/usr/share/nginx/html
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       memory: 64M
    #       cpus: '0.1'
    #     reservations:
    #       memory: 32M
    #       cpus: '0.05'
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/health"]
      interval: 60s
      timeout: 15s
      retries: 3
      start_period: 30s

  moodle:
    build: .
    container_name: moodle
    depends_on:
      - mariadb
      - redis
    expose:
      - "8080"
      - "8443"
    environment:
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_EMAIL=${MOODLE_EMAIL}
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=${MARIADB_DATABASE}
      - MOODLE_DATABASE_USER=${MARIADB_USER}
      - MOODLE_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - MOODLE_REDIS_HOST=redis
      - MOODLE_REDIS_PORT_NUMBER=6379
      - MOODLE_CACHE_STORE_SESSION=redis
      - PHP_MEMORY_LIMIT=192M           #low ram config
      - MOODLE_REVERSEPROXY=yes
      - MOODLE_SSLPROXY=yes
      - BITNAMI_DEBUG=false
    volumes:
      - ./data/moodle:/bitnami/moodle
      - ./data/moodledata:/bitnami/moodledata
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    #       cpus: '0.8'
    #     reservations:
    #       memory: 256M
    #       cpus: '0.4'
    healthcheck:
      test: ["CMD-SHELL", "curl -f -s -H 'Host: lms.vasueataxacademy.com' -H 'X-Forwarded-Proto: https' -H 'X-Forwarded-Host: lms.vasueataxacademy.com' http://localhost:8080/ || exit 1"]
      interval: 120s
      timeout: 30s
      retries: 3
      start_period: 90s

  mariadb:
    image: bitnami/mariadb:11.1
    container_name: mariadb
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - ./data/mariadb:/bitnami/mariadb
      - ./mariadb/custom-low-optimised.cnf:/opt/bitnami/mariadb/conf/my_custom.cnf:ro
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       memory: 1G
    #       cpus: '0.8'
    #     reservations:
    #       memory: 256M
    #       cpus: '0.2'
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root -p$$MARIADB_ROOT_PASSWORD --silent"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s

  redis:
    image: bitnami/redis:7.2
    container_name: redis
    ports:
      - "6379:6379"  # For checking redis insights
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    volumes:
      - ./data/redis:/bitnami/redis/data
    restart: always
    command: ["redis-server", "--maxmemory", "64mb", "--maxmemory-policy", "allkeys-lru"]
    # deploy:
    #   resources:
    #     limits:
    #       memory: 512M
    #       cpus: '0.5'
    #     reservations:
    #       memory: 64M
    #       cpus: '0.1'
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "${REDIS_PASSWORD}", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  moodlecron:
    build: .
    container_name: moodlecron
    depends_on:
      - mariadb
      - redis
      - moodle
    environment:
      - MOODLE_USERNAME=${MOODLE_USERNAME}
      - MOODLE_PASSWORD=${MOODLE_PASSWORD}
      - MOODLE_EMAIL=${MOODLE_EMAIL}
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_NAME=${MARIADB_DATABASE}
      - MOODLE_DATABASE_USER=${MARIADB_USER}
      - MOODLE_DATABASE_PASSWORD=${MARIADB_PASSWORD}
      - MOODLE_REDIS_HOST=redis
      - MOODLE_REDIS_PORT_NUMBER=6379
      - MOODLE_CACHE_STORE_SESSION=redis
    volumes:
      - ./data/moodle:/bitnami/moodle
      - ./data/moodledata:/bitnami/moodledata
    restart: always
    # deploy:
    #   resources:
    #     limits:
    #       memory: 256M
    #       cpus: '0.2'
    #     reservations:
    #       memory: 128M
    #       cpus: '0.1'
    command: >
      bash -c "
        while true; do
          echo \"[$(date)] Running Moodle cron...\"
          /opt/bitnami/php/bin/php /bitnami/moodle/admin/cli/cron.php
          echo \"[$(date)] Moodle cron completed. Sleeping for 5 minutes...\"
          sleep 300
        done
      "
    healthcheck:
      test: ["CMD", "pgrep", "-f", "bash"]
      interval: 300s
      timeout: 30s
      retries: 2


