version: '3.8'

services:
  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./nginx/ssl:/etc/letsencrypt
      - ./nginx/html:/usr/share/nginx/html
    entrypoint: ""
    command: ["tail", "-f", "/dev/null"]  # Keeps container running
    profiles:
      - ssl
    networks:
      - default

networks:
  default:
    name: moodle_default