version: '3.8'

services:
  moodle:
    image: bitnami/moodle:latest
    ports:
      - "8080:8080"
      - "8443:8443"
    environment:
      - MOODLE_USERNAME=admin
      - MOODLE_PASSWORD=adminpass
      - MOODLE_EMAIL=admin@example.com
      - MOODLE_DATABASE_HOST=mariadb
      - MOODLE_DATABASE_PORT_NUMBER=3306
      - MOODLE_DATABASE_USER=bn_moodle
      - MOODLE_DATABASE_NAME=bitnami_moodle
      - MOODLE_DATABASE_PASSWORD=moodlepass
      - BITNAMI_DEBUG=true

    volumes:
      - moodle_data:/bitnami/moodle
      - moodledata_data:/bitnami/moodledata
    depends_on:
      - mariadb

  mariadb:
    image: bitnami/mariadb:latest
    environment:
      - MARIADB_ROOT_PASSWORD=rootpass
      - MARIADB_DATABASE=bitnami_moodle
      - MARIADB_USER=bn_moodle
      - MARIADB_PASSWORD=moodlepass
      - MARIADB_CHARACTER_SET=utf8mb4
      - MARIADB_COLLATE=utf8mb4_unicode_ci
    volumes:
      - mariadb_data:/bitnami/mariadb

volumes:
  moodle_data:
  moodledata_data:
  mariadb_data:
